### ISSUE TITLE
Lab03 Review (lab09)

### ISSUE THREAD

**Issue by s247249** [FarInHeight/Computational-Intelligence#2]
Hi Davide,
first of all, I'd like to say I'm impressed with the amount of work you put in this lab: you not only managed to solve the problem with iterations 1 and 2, but almost made it with 5. I really liked how well explained your code is and how much effort you put in analizing and implementing what might help a failed attempt at a solution in iterations 5 and 10.

The implementation of extinction works like a charm to improve all results and I wish I thought about implementing it myself on my own solution.

Unfortunately, I can't help much with improving results with iterations 5 and 10. I tried to fiddle around with some parameters based on some assumptions I made and sometimes managed to get _slightly_ better results, but I can't say for sure if it was due to pure luck or not, since in those cases the change wasn't big enough or consistent.

All in all, good job and keep up the good work and good luck for your next labs!

**Comment by FarInHeight** [comment]
Thank you for your feedback 😉!
Good luck for the next labs to you too!
